[package]
name = "refract-gtk"
version = "0.6.0"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "Refract GTK is a guided AVIF/JPEG XL/WebP conversion utility for JPEG and PNG sources."
repository = "https://github.com/Blobfolio/refract"
readme = "README.md"
publish = false

[package.metadata.deb]
maintainer = "Josh Stoik <hello@blobfolio.com>"
copyright = "2021, Blobfolio, LLC <hello@blobfolio.com>"
license-file = ["../LICENSE", "0"]
revision = "1"
depends = "libgdk-pixbuf2.0-0(>= 2.36), libgtk-3-0 (>= 3.22), libpango-1.0-0, libcairo2, libatk1.0-0, libglib2.0-0, libpng16-16, libstdc++6 (>= 8.3.0), libc6 (>= 2.28)"
section = "utility"
extended-description = """\
.\n\
Refract GTK is a guided AVIF/JPEG XL/WebP conversion utility for JPEG and PNG sources, simplifying the task of finding the smallest acceptable quality.\n \
"""
assets = [
    ["../target/x86_64-unknown-linux-gnu/release/refract-gtk", "usr/bin/", "755"],
    ["./skel/deb/applications/refract-gtk.desktop", "/usr/share/applications/", "644"],
    ["./skel/deb/icons/hicolor/48x48/apps/refract-gtk.png", "/usr/share/icons/hicolor/48x48/apps/", "644"],
    ["./skel/deb/icons/hicolor/64x64/apps/refract-gtk.png", "/usr/share/icons/hicolor/64x64/apps/", "644"],
    ["./skel/deb/icons/hicolor/128x128/apps/refract-gtk.png", "/usr/share/icons/hicolor/128x128/apps/", "644"],
    ["./skel/deb/icons/hicolor/256x256/apps/refract-gtk.png", "/usr/share/icons/hicolor/256x256/apps/", "644"],
    ["./skel/deb/pixmaps/refract-gtk.png", "/usr/share/pixmaps/", "644"],
]

[dependencies]
atomic = "0.5.*"
dactyl = "0.1.*"
dowser = "0.2.*"
gio = "0.9.*"
glib = "0.10.*"

[dependencies.gdk-pixbuf]
version = "0.9.*"
features = [ "v2_36" ]

[dependencies.gtk]
version = "0.9.*"
features = [ "v3_22" ]

[dependencies.refract_core]
path = "../refract_core"
features = [ "bin", "gtk", "decode_ng" ]

[dependencies.tempfile-fast]
git = "https://github.com/FauxFaux/tempfile-fast-rs.git"
rev = "7cd84b2"
