.TH "REFRACT" "1" "May 2025" "refract v1.0.4" "User Commands"
.SH NAME
REFRACT \- Manual page for refract v1.0.4.
.SH DESCRIPTION
Guided AVIF/JPEG XL/WebP conversion for JPEG and PNG sources.
.SS USAGE:
.TP
refract [FLAGS] [OPTIONS] <PATH(s)…>
.SS FLAGS:
.TP
\fB\-e\fR, \fB\-\-exit\-auto\fR
Exit the program after the last image has been processed.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-\-no\-avif\fR
Skip AVIF encoding.
.TP
\fB\-\-no\-jxl\fR
Skip JPEG\-XL encoding.
.TP
\fB\-\-no\-lossless\fR
Skip lossless encoding passes.
.TP
\fB\-\-no\-lossy\fR
Skip lossy encoding passes.
.TP
\fB\-\-no\-webp\fR
Skip WebP encoding.
.TP
\fB\-\-no\-ycbcr\fR
Skip AVIF YCbCr encoding passes.
.TP
\fB\-s\fR, \fB\-\-save\-auto\fR
Automatically save successful conversions to their source paths — with new extensions appended — instead of popping file dialogues for confirmation.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print program version.
.SS OPTIONS:
.TP
\fB\-l\fR, \fB\-\-list\fR <FILE>
Read (absolute) image and/or directory paths from this text file — or STDIN if '\-' — one path per line, instead of or in addition to those specified inline via <PATH(S)>.
.SS TRAILING:
.TP
\fB<PATH(s)…>\fR
Image and/or directory paths to re\-encode. Directories will be crawled recursively.
