.TH "REFRACT" "1" "May 2021" "Refract v0.5.0" "User Commands"
.SH NAME
Refract \- Manual page for refract v0.5.0.
.SH DESCRIPTION
Refract is a guided AVIF/JPEG XL/WebP conversion utility for JPEG and PNG sources.
.SS USAGE:
.TP
refract [FLAGS] [OPTIONS] <PATH(s)…>
.SS FLAGS:
.TP
\fB\-b\fR, \fB\-\-browser\fR
Output an HTML page that can be viewed in a web browser to preview encoded images. If omitted, preview images will be saved directly, allowing you to view them in the program of your choosing.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-\-no\-avif\fR
Skip AVIF conversion.
.TP
\fB\-\-no\-jxl\fR
Skip JPEG XL conversion.
.TP
\fB\-\-no\-webp\fR
Skip WebP conversion.
.TP
\fB\-\-skip\-lossless\fR
Only perform lossy encoding.
.TP
\fB\-\-skip\-lossy\fR
Only perform lossless encoding.
.TP
\fB\-\-skip\-ycbcr\fR
Only test full\-range RGB AVIF encoding (when encoding AVIFs).
.TP
\fB\-V\fR, \fB\-\-version\fR
Print program version.
.SS OPTIONS:
.TP
\fB\-l\fR, \fB\-\-list\fR <FILE>
Read file paths from this text file.
.SS <PATH(S)…>:
.TP
Any number of images and directories to crawl and crunch.
